-- AlterTable
ALTER TABLE `audit_events` MODIFY `action` ENUM('VEHICLE_CREATED', 'VEHICLE_UPDATED', 'VEHICLE_DELETED', 'SESSION_SAVED', 'DTCS_CLEARED', 'REPAIR_RECORDED', 'REPAIR_VERIFIED', 'QUOTE_RECORDED', 'AI_EXPLANATION_REQUESTED', 'AI_MECHANIC_REQUESTED', 'VEHICLE_RECOGNISED', 'RATE_LIMITED') NOT NULL;

-- AlterTable
ALTER TABLE `vehicle_configurations` MODIFY `source` ENUM('USER_ENTERED', 'IMAGE_RECOGNISED', 'VIN_DECODED', 'OBD_REPORTED', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN';

-- AlterTable
ALTER TABLE `vehicle_identifications` MODIFY `source` ENUM('USER_ENTERED', 'IMAGE_RECOGNISED', 'VIN_DECODED', 'OBD_REPORTED', 'UNKNOWN') NOT NULL DEFAULT 'UNKNOWN';
