import { FlaskConical } from 'lucide-react';

import { cn } from '@/lib/utilities/cn';

/**
 * Declares that the data on screen is synthetic.
 *
 * Rule 2: a simulated diagnostic session must say so visibly. The caller
 * passes the provider's own `isSimulated` flag rather than deciding for
 * itself, so a screen cannot show simulated data while claiming otherwise.
 *
 * Renders nothing when the data is real — a permanent banner would be ignored
 * and would dilute the warning when it matters.
 */
export function SimulationBanner({
  isSimulated,
  className,
}: {
  isSimulated: boolean;
  className?: string;
}) {
  if (!isSimulated) return null;

  return (
    <div
      role="status"
      className={cn(
        'border-status-warn bg-status-warn-subtle text-status-warn flex items-start gap-3 rounded-lg border px-4 py-3',
        className,
      )}
    >
      <FlaskConical className="mt-0.5 size-4 shrink-0" aria-hidden="true" />
      <div className="min-w-0">
        <p className="font-mono text-xs font-semibold tracking-[0.12em] uppercase">
          Simulation mode
        </p>
        <p className="mt-1 text-sm">
          Every reading below is generated by a physical model. No vehicle is connected, and nothing
          here describes a real car.
        </p>
      </div>
    </div>
  );
}
